// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAksBuuuKy9IFIkIbhi7MAeLtN7tiuOTo0',
    appId: '1:181627086323:web:5552556b9a024d2e0e9e86',
    messagingSenderId: '181627086323',
    projectId: 'authorization-app-43e26',
    authDomain: 'authorization-app-43e26.firebaseapp.com',
    storageBucket: 'authorization-app-43e26.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEv2suU3S3ahpMOsAngQfSz3w3qWLgWEQ',
    appId: '1:181627086323:android:299342c7f3be383c0e9e86',
    messagingSenderId: '181627086323',
    projectId: 'authorization-app-43e26',
    storageBucket: 'authorization-app-43e26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_LM7JSo8ppHxrusXMde1W1E0AtoSqQXc',
    appId: '1:181627086323:ios:c44372a1a5ab83130e9e86',
    messagingSenderId: '181627086323',
    projectId: 'authorization-app-43e26',
    storageBucket: 'authorization-app-43e26.appspot.com',
    iosClientId: '181627086323-a8dh0fu6tk217qvg9i8c6spbqspmmkso.apps.googleusercontent.com',
    iosBundleId: 'com.example.authorizationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_LM7JSo8ppHxrusXMde1W1E0AtoSqQXc',
    appId: '1:181627086323:ios:c44372a1a5ab83130e9e86',
    messagingSenderId: '181627086323',
    projectId: 'authorization-app-43e26',
    storageBucket: 'authorization-app-43e26.appspot.com',
    iosClientId: '181627086323-a8dh0fu6tk217qvg9i8c6spbqspmmkso.apps.googleusercontent.com',
    iosBundleId: 'com.example.authorizationApp',
  );
}
